package com.example.aida.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.aida.been.Collocation;
import com.example.aida.been.ImageList;
import com.example.aida.been.User;

import com.example.aida.greendao.CollocationDao;
import com.example.aida.greendao.ImageListDao;
import com.example.aida.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collocationDaoConfig;
    private final DaoConfig imageListDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CollocationDao collocationDao;
    private final ImageListDao imageListDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collocationDaoConfig = daoConfigMap.get(CollocationDao.class).clone();
        collocationDaoConfig.initIdentityScope(type);

        imageListDaoConfig = daoConfigMap.get(ImageListDao.class).clone();
        imageListDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        collocationDao = new CollocationDao(collocationDaoConfig, this);
        imageListDao = new ImageListDao(imageListDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Collocation.class, collocationDao);
        registerDao(ImageList.class, imageListDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        collocationDaoConfig.clearIdentityScope();
        imageListDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CollocationDao getCollocationDao() {
        return collocationDao;
    }

    public ImageListDao getImageListDao() {
        return imageListDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
